from src.utils.db import get_connection


def ensure_fulltext_search(cur) -> None:
    """
    Add a full-text search column and index to `documents` (safe to re-run).

    `ts` is generated by Postgres from chunk_text, so it stays in sync with
    every insert automatically and needs no change to the ingestion code.
    """

    cur.execute("""
        ALTER TABLE documents
        ADD COLUMN IF NOT EXISTS ts tsvector
        GENERATED ALWAYS AS (to_tsvector('english', chunk_text)) STORED;
    """)

    cur.execute("""
        CREATE INDEX IF NOT EXISTS documents_ts_idx
        ON documents USING GIN (ts);
    """)


def main():

    conn = get_connection()
    cur = conn.cursor()

    ensure_fulltext_search(cur)
    conn.commit()

    cur.execute("SELECT count(*) FROM documents WHERE ts IS NOT NULL")
    print(f"Full-text search ready for {cur.fetchone()[0]} chunks")

    cur.close()
    conn.close()


if __name__ == "__main__":
    main()
